### PR TITLE
Created pullrequest.md for issue #27

### PR DESCRIPTION
**Pull request by dNhunter3107**

### CODE REVIEW

**Comment by comoser** [comment]
@dNhunter3107 I was thinking more of a template like the following:

```markdown
<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Related Issue
<!--- This project only accepts pull requests related to open issues -->
<!--- If suggesting a new feature or change, please discuss it in an issue first -->
<!--- If fixing a bug, there should be an issue describing it with steps to reproduce -->
<!--- Please link to the issue here and follow an appropriate verb that will automatically solve the issue: -->
<!--- e.g: Closes #123 -->

## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->

## Screenshots (if appropriate):

## Types of changes
<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
```

**Comment by dNhunter3107** [comment]
You are going to update the template or shall I do it?

**Comment by comoser** [comment]
> You are going to update the template or shall I do it?

Please update your PR 🙏

**Comment by comoser** [comment]
Closed in favor of #33

**Pull request closed without merging**
