### PR TITLE
chore(husky): add husky and conventional commits as standard

### LINKED ISSUE #29: Setup husky to only allow conventional commits on the repository
We need to formalize the commit convention, and using conventional commits will help with this.

### PR DESCRIPTION
**Pull request by comoser**
## Description

- Add husky and `commit-msg` hook
- Enforce conventional commits for the repo
- Fix name for PR template in the repo

## Related Issue

Closes #29 

## Motivation and Context

This change will improve commit consistency and improve readability when searching the commit history

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by tiagomichaelsousa — APPROVED** [review]
We can also add this validation to the PR's titles with a workflow, what do you think?  👀

**Comment by comoser** [comment]
> We can also add this validation to the PR's titles with a workflow, what do you think? 👀

That would be awesome! Want to create the issue? 🙏

**Comment by tiagomichaelsousa** [comment]
> > We can also add this validation to the PR's titles with a workflow, what do you think? 👀
> 
> That would be awesome! Want to create the issue? 🙏

Already did #38 😎

Do you want me to create the issues for the release drafter and label checker as well?

**Comment by comoser** [comment]
> > > We can also add this validation to the PR's titles with a workflow, what do you think? 👀
> > 
> > 
> > That would be awesome! Want to create the issue? 🙏
> 
> Already did #38 😎
> 
> Do you want me to create the issues for the release drafter and label checker as well?

Please do!! 🙏🙏

**Pull request merged**
